---
project_name: AirbusShipDetection
experiment_name: test_task_run

seed: 42
num_workers: 4

data:
  images_dir: data/train_v2_short
  train_csv_path: data/train_ship_segmentations_v2_short.csv
  val_csv_path: data/train_ship_segmentations_v2_short.csv

criterion:
  type: segmentation_models_pytorch.utils.losses.DiceLoss

metric:
  type: segmentation_models_pytorch.utils.metrics.IoU
  threshold: 0.5

optimizer:
  type: torch.optim.Adam
  lr: 0.0005

scheduler:
  type: torch.optim.lr_scheduler.OneCycleLR
  div_factor: 10
  final_div_factor: 10000
  verbose: True

callbacks:
  stopper:
    type: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 5
    verbose: True
    mode: min

  lr_monitor:
    type: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

  checkpoint:
    type: pytorch_lightning.callbacks.ModelCheckpoint
    filename: "{epoch}-{val_loss_epoch:.2f}-{other_metric:.2f}"
    monitor: val_metrics_epoch
    verbose: True
    mode: max
    save_top_k: -1

model:
  type: segmentation_models_pytorch.FPN
  encoder_name: efficientnet-b3
  activation: sigmoid
  encoder_weights: imagenet
  in_channels: 3
  classes: 1

params:
  epochs: 20
  batch_size: 16
  image_size: 256
